// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
export {}
        
declare module 'vue' {
  export interface GlobalComponents {
    DialogContainer: typeof import('./src/components/DialogContainer/index.vue')['default']
    ElButton: typeof import('element-ui/lib/button')['default']
    ElDialog: typeof import('element-ui/lib/dialog')['default']
    ElLink: typeof import('element-ui/lib/link')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toggle: typeof import('./src/components/Toggle/toggle.vue')['default']
  }
}
